users:
  darwin:
    displayname: "Darwin Muñoz"
    password: "$argon2id$v=19$m=65536,t=3,p=4$lYz3xR+srlUyiXiYWCDixw$DIG9xkQ4L+jLMiMRDnIISOHg9yJYoyer4M8goXIBxiQ"  
    # genera con 
    # docker run --rm authelia/authelia \
    # authelia crypto hash generate argon2 \
    # --password "demo8.8"
    email: darwin@example.com
    groups:
      - admins
